### PR TITLE
Adding Python f-string syntax support

### PR DESCRIPTION
**Pull request by samstrohkorbatt**
Adding [Python f-string](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) support, as mentioned in issue: [microsoft/monaco-languages#1762](https://github.com/microsoft/monaco-editor/issues/1762)

This includes new tests for the f-string formatting, and all current string tests are passing, so these changes are isolated to only f-strings

### CODE REVIEW

**Comment by samstrohkorbatt** [comment]
@microsoft-github-policy-service agree [company="{AT&T}"]

**Comment by samstrohkorbatt** [comment]
@microsoft-github-policy-service agree company="AT&T"

**Comment by samstrohkorbatt** [comment]
Hi @hediet and @alexdima,
Would either of you two be able to review this PR? It's been open for 2 weeks without any feedback so far

Best,
Sam

**Comment by samstrohkorbatt** [comment]
Hi @rzhao271, @hediet, and @alexdima,
Could any of you review this PR? It's been open for 6 weeks now and no one has provided any feedback yet

Best,
Sam

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
Thanks for the PR! And sorry for the delay.

**Review by sandy081 — APPROVED** [review]

**Pull request merged**
