### PR TITLE
Support hyphenated HTML tags in Markdown syntax

### LINKED ISSUE #2863: [Feature Request] Support syntax highlighting of <custom-component>in markdown
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Currently, markdown only supports html/tag without `-`, which does not support `<custom-component>` `</custom-component>` properly.

```html
<!-- correct syntax highlighting in markdown -->
<div></div>

<!-- incorrect syntax highlighting in markdown -->
<x-div></x-div>
```

### PR DESCRIPTION
**Pull request by rcjsuen**
This fixes #2863.

### CODE REVIEW

**Comment by hediet** [comment]
Thanks for your PR!

**Comment by rcjsuen** [comment]
@hediet Thanks for the review. Have a nice day! :)

**Comment by andrewspy** [comment]
I have tried with the latest (v0.32.1) release, but the syntax highlighting of `<custom-component>` still not working as expected. Am I missing anything?

**Comment by rcjsuen** [comment]
> I have tried with the latest (v0.32.1) release, but the syntax highlighting of `<custom-component>` still not working as expected. Am I missing anything?

@andrewspy It seems to work on the website for me.

image

**Comment by andrewspy** [comment]
@rcjsuen You are right! Sorry for asking the stupid question before testing it on the main site. I'll check my toolchains.

Thanks!

**Comment by andrewspy** [comment]
@rcjsuen Is there an API to get the version string of Monaco Editor? Need it to make sure I'm using the latest version, and I can't seem to find it in the [API DOC](https://microsoft.github.io/monaco-editor/api/index.html)

Sorry to bother you again.

**Comment by rcjsuen** [comment]
> Is there an API to get the version string of Monaco Editor? Need it to make sure I'm using the latest version, and I can't seem to find it in the [API DOC](https://microsoft.github.io/monaco-editor/api/index.html)

Not sure. Maybe you can look at your `node_modules` folder and check the `markdown.ts` file to see if you've gotten the change for starters.

**Comment by andrewspy** [comment]
@rcjsuen Managed to resolve the issue, I am using `@monaco-editor/loader`, and it was loading an older version of the code online.

Thanks!

**Pull request merged**
