### PR TITLE
doc: (samples) Simplify Browser ESM Parcel build

### PR DESCRIPTION
**Pull request by resistdesign**
A PR as per: https://github.com/microsoft/monaco-editor/issues/2823#issuecomment-993706028

### CODE REVIEW

**Comment by rgraffbrd** [comment]
@alexdima @hediet Please let me know if this is sufficient 🙂

**Comment by resistdesign** [comment]
@alexdima @hediet Please let me know if this is sufficient 🙂

**Comment by hediet** [comment]
Didn't test the sample, but the code looks code. Thank you!

**Comment by resistdesign** [comment]
> Didn't test the sample, but the code looks code. Thank you!

Not a problem, I hope it makes things easier for others getting started 🙂

**Comment by alexdima** [comment]
I tested it locally, works great! Thanks again!

**Pull request merged**
