### PR TITLE
Added Bower package with release folder

### PR DESCRIPTION
**Pull request by michael-golfi**
I've added what's needed to make this a bower package. I also registered the package.

To install it:
```bash
bower install monaco-editor
```

Currently, this package install points to github.com/michael-golfi/monaco-editor-1 but I will change it as soon as the changes are merged.

In detail, the only changes that were made was exclusing the release folder from the .gitignore so that each time a commit is tagged, it will be considered the latest release by bower and then bower will download the entire repo including the release folder.

I'm not sure how this all meshes with the set up for npm as I've never published an npm package. I also updated the version to 0.7.1 since bower was defaulting to 0.7.0 which did not have the patched .gitignore file.

### CODE REVIEW

**Comment by michael-golfi** [comment]
In reference to #138 and @mattgodbolt

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by mattgodbolt** [comment]
It would be super convenient to get this PR integrated: I'm currently using @michael-golfi 's separate repo to pull monaco into my project. This would be a much better solution. (Thanks @michael-golfi !)

**Comment by paresy** [comment]
+1

**Comment by chriswoodle** [comment]
Can this get merged or something? looks like @michael-golfi 's repo is gone.

**Comment by alexandrudima** [comment]
IMHO, this is not a good solution, as it adds all the files to the repo...

**Pull request closed without merging**
