### PR TITLE
Fix issue #3123

### PR DESCRIPTION
**Pull request by Mekomancer**
Fix issue #3123

### CODE REVIEW

**Comment by hediet** [comment]
Thanks for the PR! Can you add some tests?

**Review by hediet — CHANGES_REQUESTED** [review]
Please add some tests, so this doesn't break again.

**Review by Mekomancer — COMMENTED** [review]
make sure everything is good

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
Unfortunately, the tests don't seem to pass. I'll close the PR for now, please reopen it if you manage to fix the tests. Thanks!

**Pull request closed without merging**
