### PR TITLE
Updated vscode-json-languageservice to 5.3.9

### PR DESCRIPTION
**Pull request by harrismirza**
Updated vscode-json-languageservice to the latest version, in order to fix the bug where validating JSON against the latest JSON Schema Drafts would not work correctly (https://github.com/microsoft/vscode-json-languageservice/issues/122)

### CODE REVIEW

**Comment by harrismirza** [comment]
@microsoft-github-policy-service agree

**Review by DayalVekeria — APPROVED** [review]

**Review by elisherer — APPROVED** [review]

**Comment by harrismirza** [comment]
I'm just doing some additional testing here to make sure there are no bugs.

**Review by brenbar — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by daviesgeek** [comment]
Wondering if this will be included in the March release, am heavily invested in seeing support for 2020-12 schema support. Am willing to help out in any way I can.

**Comment by harrismirza** [comment]
Hey @aeschli, @deepak1556,

Is there a reason this wasn't included with the March release? I was looking forward to using this.

Even though this doesn't include full schema 2020-12 support, currently just having the schema property set to anything newer than draft-07 completely breaks validation.

**Comment by harrismirza** [comment]
Hey, sorry to keep asking about this, but is there a particular reason this merge keeps being pushed?

**Comment by jrsquared** [comment]
Same question. I've been telling customers that it is coming, first in March, then April, and now May.

**Comment by daviesgeek** [comment]
Same here

**Comment by hediet** [comment]
Thanks for the PR and sorry for the delay! Just updated all of the langugae services.

**Comment by jrsquared** [comment]
Why didn't the update to languageservices make it in 0.49?

**Comment by elisherer** [comment]
Seems like publishing is not done by CI/CD, so maybe someone forgot to update node modules before publishing... 🙄

**Comment by jrsquared** [comment]
@hediet Can we confirm that this will make it into the 0.50 release?

**Comment by elisherer** [comment]
Seems to be added to 0.50.0 (using 5.3.11)

But, I get the error
```json
{
"$schema": "https://json-schema.org/draft/2019-09/schema",
// The schema uses meta-schema features ($recursiveRef) that are not yet supported by the validator
}
```

**Pull request closed without merging**
