### PR TITLE
Update TypeScript to TS 5.4.5 in all projects, vendored files

### PR DESCRIPTION
**Pull request by johnyanarella**
This commit updates the version of TypeScript vendored into the monaco-editor (via `npm run import-typescript`) to the latest version (5.3.3). It also aligns the explicit TypeScript dependencies throughout the repo for "typescript" to match.

This upgrade is essential to ensure monaco-editor can provide accurate diagnostics for JSX when using the latest React types (ex. via `addExtraLib()`), given the [introduction of JSX.ElementType](https://blog.logrocket.com/declaring-jsx-types-typescript-5-1/) and associated changes to TypeScript support for JSX introduced in [TypeScript 5.1](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#decoupled-type-checking-between-jsx-elements-and-jsx-tag-types).

cc: @jakebailey (as this follows your example from #3721)

### CODE REVIEW

**Comment by johnyanarella** [comment]
@microsoft-github-policy-service agree

**Comment by wirekang** [comment]
VSCode already supported TypeScript 5.3 few months ago. Why this PR is hanging so long?

**Comment by johnyanarella** [comment]
Updated to upgrade to TypeScript v5.4.2 now.

Recapping - the changes introduced by this PR were:

- bumping the version of TypeScript in all of the `package.json` files
- running `npm i` and `yarn install` (for the website) for the affected packages
- executing the pre-existing `import-typescript` from the root package.json to generate the vendored files

I completely understand if it is awkward to accept the MR given the large amount of generated / vendor code. Perhaps a maintainer could pull this PR locally and then re-run the import-typescript script to validate that the PR contains the unmodified outcome of the script your team created (i.e. no changes to commit).

**Comment by johnyanarella** [comment]
@hediet Noticed your recent bumps to other dependencies. Can you help with this? (see also #4412)

**Comment by jakebailey** [comment]
FWIW you probably want to wait for 5.4.4, just because it has some critical bugfixes.

**Comment by johnyanarella** [comment]
Updated to upgrade to TypeScript v5.4.4 now.

**Comment by johnyanarella** [comment]
Updated PR to upgrade to TypeScript v5.4.5 now.

**Comment by IMax153** [comment]
Is there any progress on this PR? Will we have access to the updated TS version at some point soon?

**Review by hediet — APPROVED** [review]

**Comment by hediet** [comment]
Thanks! Sorry for the delay!

**Comment by IMax153** [comment]
@hediet - apologies for the ping, but does this need approval from another maintainer? 

It looks like CI is locked up on `Community PR Approvals`.

**Review by alexr00 — APPROVED** [review]

**Comment by alexr00** [comment]
Delay was on me. I was reviewing and noticed an issue while doing so, and then I used this PR to investigate the issue I was seeing.

**Comment by IMax153** [comment]
> Delay was on me. I was reviewing and noticed an issue while doing so, and then I used this PR to investigate the issue I was seeing.

Thank you both so much for getting this PR over the finish line :)

**Comment by hax** [comment]
We use this PR several months, glad to see it finally be merged, hope the new version will be released soon so we can switch back to the official release. Thank you!

**Pull request merged**
