### PR TITLE
Doc/simplify browser esm parcel

### PR DESCRIPTION
**Pull request by resistdesign**
A PR to update the Browser ESM Parcel sample as per: https://github.com/microsoft/monaco-editor/issues/2823#issuecomment-993706028

### CODE REVIEW

**Comment by hediet** [comment]
Thank you for this PR!
It would be awesome if you could add `.idea/` to the ignore file in a separate PR though, so that the history reads nicely.

**Comment by resistdesign** [comment]
Ok, I can do that later today 🙂

**Comment by resistdesign** [comment]
Closing in favor of a cleaner PR.

**Comment by alexdima** [comment]
Here's also a trick I use a lot in case I ever want to ignore a folder completely in a git repository without touching the top level `.gitignore`: just add a `.gitignore` file in the folder you want completely ignored with the content `*`.

**Comment by resistdesign** [comment]
Whoa! Brilliant!

**Pull request closed without merging**
