### PR TITLE
Update typescript to 4.8.4

### PR DESCRIPTION
**Pull request by SferaDev**
Ideally `monaco` should allow customising the TypeScript version, 4.5.5 has several months and newer features are not available.

In the jump to 4.8, `InlayHintsOptions` has been removed and merged inside `UserPreferences`, not sure if you want to build a sub-type.

### CODE REVIEW

**Comment by SferaDev** [comment]
@microsoft-github-policy-service agree [company="Xata"]

**Comment by SferaDev** [comment]
@microsoft-github-policy-service agree company="Xata"

**Comment by wycats** [comment]
Is there any motion on this?

Since TS 5.0 is on the horizon, has there been any more thought on making the version of TypeScript used in monaco customizable at runtime?

**Comment by VladSez** [comment]
cc @hediet

**Comment by jakebailey** [comment]
FYI #3721 just merged which brings in TS 5.0; you can likely close this!

**Pull request closed without merging**
