### PR TITLE
Update Swift language specification to version 5.5

### PR DESCRIPTION
**Pull request by philipturner**
See #2854

### CODE REVIEW

**Review by hediet — APPROVED** [review]

**Comment by philipturner** [comment]
@hediet it should be fixed now.

**Comment by hediet** [comment]
Please fix the unit tests, then I can merge the PR.

**Comment by philipturner** [comment]
Should be fixed now, but I can’t run the unit tests on my personal computer rn

**Comment by philipturner** [comment]
Ready to merge?

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
