### PR TITLE
Add `customWorkerFactory` to customize tsworker directly

### PR DESCRIPTION
**Pull request by x6eull**
Add a way to customize typescript worker in module workers, avoiding importScripts (which the customWorkerPath uses to extend the typescript worker).

Hoping to provide some progress to https://github.com/microsoft/monaco-editor/issues/3151.

### CODE REVIEW

**Comment by LonelyDagger** [comment]
@microsoft-github-policy-service agree

**Comment by hediet** [comment]
Afaik this does not work, as `createData` must be serializable. You cannot send over your customization function from the page to the worker.

**Review by hediet — APPROVED** [review]
I think it is a little bit ugly that you pass in unserializable data into the create function to override the TypeScriptWorker (and I hope nobody tries to pass in this data from the host side that creates the worker), but I don't see a much nicer solution.

**Review by chrmarti — APPROVED** [review]

**Comment by x6eull** [comment]
@microsoft-github-policy-service agree

**Comment by hediet** [comment]
I actually think https://github.com/microsoft/monaco-editor/pull/3488 is a better solution.

**Comment by x6eull** [comment]
I had no idea that `createData` must be serializable when I created the pr. I couldn't build a complete package and test it, so I just followed the step of `customWorkerPath`. If `createData` must be serializable, this approach won't work since I intend to use it in the script that create the worker (as well as the editor).

**Comment by hediet** [comment]
>  If createData must be serializable,

It does not have to be serializable when called from a script that imports the worker, but the data the host passes in has to be serializable. So it would have worked in your use-case, but it could confuse users.
https://github.com/microsoft/monaco-editor/pull/3488 just exports everything needed for a solution that does not cause this confusion.

Thanks for coming up with this PR anyway! :)

**Pull request closed without merging**
