### PR TITLE
Bump vscode-json-languageservice to v5.3.11

### LINKED ISSUE #3625: [Feature Request] Bump "vscode-json-languageservice" to 5.3.1
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Would it be possible to bump the version of the json languageservice to 5.3.1? Right now it has an old version that does not validate any of the "newer" json schemas. With this new version (I have tested locally) it validates fine .

### Monaco Editor Playground Link

_No response_

### Monaco Editor Playground Code

_No response_

### PR DESCRIPTION
**Pull request by MakakWasTaken**
Bumps [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice) to version 5.3.7 to bring partial support for `2020-12` & `2019-09`, which was introduced in 5.0.0.

Fixes #3625 (It does however bump to 5.3.7 instead of 5.3.1)

### CODE REVIEW

**Comment by MakakWasTaken** [comment]
@microsoft-github-policy-service agree

**Review by elisherer — APPROVED** [review]

**Comment by elisherer** [comment]
Can someone please fix and merge this? I'm working with a lot of schema editing and this feature means a lot!

**Comment by harrismirza** [comment]
> Can someone please fix and merge this? I'm working with a lot of schema editing and this feature means a lot!

@elisherer I've actually raised another PR for this, please review and we can get it merged

https://github.com/microsoft/monaco-editor/pull/4354

**Review by klmhyeonwoo — APPROVED** [review]

**Comment by MakakWasTaken** [comment]
I suspect that this might already have been fixed in some other push. The version is at least now set to 5.3.11

**Pull request closed without merging**
